package com.rickyslash.pinkfloydcompose.model

object AlbumsDataSource {
    val albumsData = listOf(
        Album(1, "The Piper at the Gates of Dawn", "5 August 1967", "Interstellar Overdrive", "https://upload.wikimedia.org/wikipedia/en/3/3c/PinkFloyd-album-piperatthegatesofdawn_300.jpg",
            "\"'The Piper at the Gates of Dawn' is the debut album by the iconic English rock band Pink Floyd, released in 1967. The album is named after a chapter in the book 'The Wind in the Willows' and features an eclectic mix of psychedelic rock, experimental sounds, and whimsical lyrics. It showcases the band's early musical explorations and includes several standout tracks such as 'Astronomy Domine', 'Interstellar Overdrive', and 'The Gnome'.\\n\\nThe album's innovative sound and style established Pink Floyd as one of the key players in the emerging psychedelic rock scene of the late 1960s. The Piper at the Gates of Dawn is often cited as a landmark album in the history of rock music and has influenced countless musicians over the years. Its enduring popularity is a testament to the band's artistic vision and the enduring appeal of its groundbreaking sound.\""),
        Album(2, "A Saucerful of Secrets", "June 28, 1968", "Let There Be More Light", "https://upload.wikimedia.org/wikipedia/en/5/54/Saucerful_of_secrets2.jpg",
            "'A Saucerful of Secrets' is the second album by Pink Floyd, released in 1968. It marks a transitional period for the band, as it is the last album to feature founding member Syd Barrett and the first to feature new member David Gilmour. The album features a diverse range of musical styles, including psychedelic rock, space rock, and avant-garde sounds. Its standout tracks include the title track, 'Set the Controls for the Heart of the Sun', and 'Jugband Blues', the last song written by Barrett for Pink Floyd.\n\nThe album showcases the band's willingness to experiment with new sounds and styles, while still retaining the psychedelic rock sound that they had become known for. A Saucerful of Secrets has become a fan favorite over the years and is often regarded as one of Pink Floyd's best albums, due to its groundbreaking sound and its historical significance as a bridge between the band's early period with Barrett and its later period with Gilmour."),
        Album(3, "More", "June 13, 1969", "Green is the Colour", "https://upload.wikimedia.org/wikipedia/en/4/40/MoreCover.jpg",
            "'More' is the third studio album by Pink Floyd, released in 1969. The album was recorded for the film of the same name directed by Barbet Schroeder. It features a diverse range of musical styles, from acoustic folk to experimental rock, and includes some of the band's most memorable tracks such as 'Cirrus Minor', 'The Nile Song', and 'Green Is the Colour'.\n\n'More' is often considered a transitional album in Pink Floyd's career, as it marked a shift from their psychedelic sound towards a more experimental and progressive style. It also marked the departure of founding member Syd Barrett and the arrival of new member David Gilmour, who would become an integral part of the band's sound in the years to come."),
        Album(4, "Ummagumma", "November 7, 1969", "Careful With That Axe, Eugene", "https://upload.wikimedia.org/wikipedia/en/1/16/PinkFloyd-album-ummagummastudio-300.jpg",
            "'Ummagumma' is the fourth studio album by Pink Floyd, released in 1969. The album consists of two parts: a live album showcasing the band's live performances, and a second album featuring solo compositions by each member of the band. The live album was recorded during Pink Floyd's 1969 US tour and features some of their most popular songs, including 'Careful with That Axe, Eugene' and 'Set the Controls for the Heart of the Sun'. The second album is a departure from the band's previous work and features experimental and avant-garde compositions that showcase each member's individual musical styles.\n\n'Ummagumma' received mixed reviews upon its release but has since gained a cult following among Pink Floyd fans. It is considered a transitional album for the band, showcasing their evolution from a psychedelic rock band to a more experimental and progressive rock sound."),
        Album(5, "Atom Heart Mother", "October 2, 1970", "Summer '68", "https://upload.wikimedia.org/wikipedia/en/2/2e/AtomHeartMotherCover.jpeg",
            "'Atom Heart Mother' is the fifth studio album by Pink Floyd, released in 1970. The album features a combination of progressive rock, orchestral arrangements, and experimental soundscapes. Its title track, a 23-minute long epic, was the band's first attempt at a full-length orchestral piece and features contributions from the Philip Jones Brass Ensemble and choir. Other standout tracks include 'Summer 68' and 'Fat Old Sun'.\n\n'Atom Heart Mother' is considered to be one of Pink Floyd's most ambitious and experimental albums, showcasing the band's willingness to push boundaries and explore new musical territory. Despite receiving mixed reviews upon its release, the album has since become a cult classic and a favorite among many Pink Floyd fans."),
        Album(6, "Relics", "May 14, 1971", "Arnold Layne", "https://upload.wikimedia.org/wikipedia/en/1/18/Pink_Floyd_Relics_1971.jpg",
            "'Relics' is a compilation album by the famous British rock band Pink Floyd, released in 1971. The album features some of the band's early singles, B-sides, and other rarities from their first few years, including Syd Barrett-era tracks like 'Arnold Layne' and 'See Emily Play.' The album also includes several non-album singles, such as 'It Would Be So Nice' and 'Point Me at the Sky.'\n\n'Relics' provides an interesting snapshot of Pink Floyd's early career and showcases the band's evolution from their psychedelic roots to their more experimental sound. While some of the tracks may feel a bit dated, the album is still a must-listen for any Pink Floyd fan or anyone interested in the history of rock music."),
        Album(7, "Meddle", "October 30, 1971", "Echoes", "https://upload.wikimedia.org/wikipedia/en/d/d4/MeddleCover.jpeg",
            "'Meddle' is the sixth studio album by Pink Floyd, released in 1971. The album features some of the band's most iconic tracks, such as 'One of These Days' and 'Echoes', which helped establish Pink Floyd as one of the most influential bands of their time. The album also includes more experimental tracks, such as 'A Pillow of Winds' and 'Fearless', which showcase the band's willingness to push the boundaries of rock music.\n\n'Meddle' is often regarded as a transitional album for Pink Floyd, as it marks the beginning of the band's more experimental period. The album's mix of psychedelic rock, progressive rock, and avant-garde influences helped pave the way for the band's later masterpieces, such as 'Dark Side of the Moon' and 'Wish You Were Here'. Overall, 'Meddle' remains a cornerstone of Pink Floyd's discography and a must-listen for any fan of progressive rock."),
        Album(8, "Obscured by Clouds", "June 2, 1972", "Wots... Uh The Deal", "https://upload.wikimedia.org/wikipedia/en/e/ef/Pink_Floyd_-_Obscured_by_Clouds.jpg",
            "'Obscured by Clouds' is the seventh studio album by Pink Floyd, released in 1972. The album was recorded as a soundtrack for the French film 'La Vallée' and features a more straightforward and accessible sound compared to some of the band's earlier and later works. The album includes tracks such as 'Free Four', 'Wot's… Uh the Deal?', and 'Childhood's End', which showcase the band's ability to create catchy, melodic rock music without sacrificing their signature sound.\n\n'Obscured by Clouds' may not be as iconic as some of Pink Floyd's other albums, but it remains a solid and enjoyable listen for both fans and newcomers alike. The album's mix of psychedelic rock, folk-inspired melodies, and more traditional rock elements helped bridge the gap between the band's earlier and later works and cemented their place as one of the most innovative and influential bands of the 20th century."),
        Album(9, "The Dark Side of the Moon", "March 1, 1973", "Eclipse", "https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png",
            "'The Dark Side of the Moon' is the eighth studio album by Pink Floyd, released in 1973. The album is widely regarded as one of the greatest and most influential rock albums of all time and is known for its innovative use of sound effects, studio experimentation, and complex concept album structure. The album includes iconic tracks such as 'Money', 'Time', and 'Us and Them', which explore themes of greed, mortality, and the human condition.\n\n'The Dark Side of the Moon' marked a significant departure from Pink Floyd's earlier works and established them as one of the most innovative and influential bands of the 1970s. The album's seamless blend of psychedelic rock, progressive rock, and avant-garde influences, combined with its thought-provoking lyrics and stunning visual design, helped redefine the possibilities of rock music and inspired countless musicians in the years that followed. Even today, 'The Dark Side of the Moon' remains a timeless masterpiece and a must-listen for any music lover."),
        Album(10, "Wish You Were Here", "September 12, 1975", "Shine On You Crazy Diamond", "https://upload.wikimedia.org/wikipedia/en/a/a4/Pink_Floyd%2C_Wish_You_Were_Here_%281975%29.png",
            "'Wish You Were Here' is the ninth studio album by Pink Floyd, released in 1975. The album is dedicated to the band's former member Syd Barrett, who had left the band several years earlier due to mental health issues. The album features iconic tracks such as the title track 'Wish You Were Here' and 'Shine On You Crazy Diamond', which are both tributes to Barrett, as well as 'Welcome to the Machine' and 'Have a Cigar'.\n\n'Wish You Were Here' is widely regarded as one of Pink Floyd's greatest works and a masterpiece of progressive rock. The album's complex concept, which explores themes of absence, disillusionment, and the music industry, combined with the band's signature sound and stunning instrumental performances, helped redefine the possibilities of rock music and cemented Pink Floyd's place as one of the most innovative and influential bands of all time."),
        Album(11, "Animals", "January 21, 1977", "Pigs (Three Different Ones),", "https://upload.wikimedia.org/wikipedia/en/7/74/Pink_Floyd-Animals-Frontal.jpg",
            "'Animals' is the tenth studio album by Pink Floyd, released in 1977. The album is known for its use of animal metaphors to criticize the social and political conditions of late 1970s Britain. The album features tracks such as 'Dogs', 'Pigs (Three Different Ones)', and 'Sheep', which explore themes of inequality, conformity, and revolution.\n\n'Animals' is often regarded as one of Pink Floyd's darkest albums and a reflection of the band's disillusionment with the music industry and society at large. The album's mix of progressive rock, hard rock, and blues influences, combined with its thought-provoking lyrics and stunning visual design, helped establish Pink Floyd as one of the most innovative and influential bands of the 1970s. Even today, 'Animals' remains a powerful and timely commentary on the state of the world."),
        Album(12, "The Wall", "November 30, 1979", "Another Brick in the Wall", "https://upload.wikimedia.org/wikipedia/en/1/13/PinkFloydWallCoverOriginalNoText.jpg",
            "'The Wall' is the eleventh studio album by Pink Floyd, released in 1979. The album is a rock opera that tells the story of a rock star's descent into madness and isolation. The album features iconic tracks such as 'Another Brick in the Wall (Part II)', 'Comfortably Numb', and 'Hey You', which explore themes of alienation, trauma, and the destructive nature of fame.\n\n'The Wall' is widely regarded as one of Pink Floyd's greatest works and a masterpiece of rock opera. The album's complex concept, which was later adapted into a film, combined with the band's signature sound and stunning instrumental performances, helped redefine the possibilities of rock music and cemented Pink Floyd's place as one of the most innovative and influential bands of all time. Even today, 'The Wall' remains a powerful and timeless commentary on the human condition."),
        Album(13, "The Final Cut", "March 21, 1983", "The Final Cut", "https://upload.wikimedia.org/wikipedia/en/e/e4/FloydFC-Cover01.jpg",
            "'The Final Cut' is the twelfth studio album by Pink Floyd, released in 1983. The album is a concept album that focuses on the aftermath of the Falklands War and the impact of war on individuals and society. The album features tracks such as 'The Final Cut', 'Not Now John', and 'The Fletcher Memorial Home', which explore themes of loss, grief, and political disillusionment.\n\n'The Final Cut' is often regarded as a continuation of the themes explored in 'The Wall' and a reflection of the band's growing political activism. The album's mix of progressive rock, orchestral arrangements, and poignant lyrics, combined with its stunning visual design, helped establish Pink Floyd as one of the most innovative and influential bands of the 1980s. While not as commercially successful as some of the band's earlier works, 'The Final Cut' remains a powerful and poignant statement on the human cost of war."),
        Album(14, "A Momentary Lapse of Reason", "September 7, 1987", "Learning to Fly", "https://upload.wikimedia.org/wikipedia/en/4/4e/MLoRLP01.jpg",
            "'A Momentary Lapse of Reason' is the thirteenth studio album by Pink Floyd, released in 1987. The album is the first to be released after the departure of the band's iconic member Roger Waters and is seen as a return to the band's roots in progressive rock. The album features tracks such as 'Learning to Fly', 'On the Turning Away', and 'Sorrow', which showcase the band's signature sound and musical experimentation.\n\n'A Momentary Lapse of Reason' is often regarded as a transitional album for Pink Floyd, as it marked the beginning of a new era for the band. The album's mix of progressive rock, electronic music, and blues influences, combined with its stunning visual design and innovative use of technology, helped establish Pink Floyd as one of the most innovative and influential bands of the 1980s. While not as conceptually complex as some of the band's earlier works, 'A Momentary Lapse of Reason' remains a powerful and memorable album that showcases the band's enduring creativity and musical prowess."),
        Album(15, "The Division Bell", "March 28, 1994", "High Hopes", "https://upload.wikimedia.org/wikipedia/en/6/6e/Pink_Floyd_-_Division_Bell.jpg",
            "'The Division Bell' is the fourteenth and final studio album by Pink Floyd, released in 1994. The album is a concept album that explores themes of communication, relationships, and the human condition. The album features tracks such as 'High Hopes', 'Coming Back to Life', and 'Poles Apart', which showcase the band's signature sound and musical experimentation.\n\n'The Division Bell' is often regarded as a return to form for Pink Floyd, as it marked the band's reunion with longtime collaborator Richard Wright and a renewed focus on musical collaboration and experimentation. The album's mix of progressive rock, electronic music, and atmospheric soundscapes, combined with its stunning visual design and innovative use of technology, helped establish Pink Floyd as one of the most innovative and influential bands of the 1990s. Even today, 'The Division Bell' remains a powerful and memorable album that showcases the band's enduring creativity and musical prowess."),
        Album(16, "The Endless River", "November 7, 2014", "Louder Than Words", "https://upload.wikimedia.org/wikipedia/en/b/be/Pink_Floyd_-_The_Endless_River_%28Artwork%29.jpg",
            "'The Endless River' is the fifteenth and final studio album by Pink Floyd, released in 2014. The album is a tribute to the band's late keyboardist Richard Wright and features unreleased material recorded during the sessions for 'The Division Bell'. The album is predominantly instrumental and features tracks such as 'It's What We Do', 'Sum', and 'Louder Than Words', which showcase the band's signature sound and musical experimentation.\n\n'The Endless River' is often regarded as a final farewell to Pink Floyd and a celebration of the band's enduring legacy. The album's mix of ambient music, progressive rock, and atmospheric soundscapes, combined with its stunning visual design and innovative use of technology, helped establish Pink Floyd as one of the most innovative and influential bands of all time. Even today, 'The Endless River' remains a powerful and poignant tribute to the band's extraordinary career and the enduring power of their music.")
        )
}