package com.rickyslash.pinkfloydcompose.model

object AlbumsDataSource {
    val albumsData = listOf(
        Album(1, "The Piper at the Gates of Dawn", "5 August 1967", "Interstellar Overdrive", "https://upload.wikimedia.org/wikipedia/en/3/3c/PinkFloyd-album-piperatthegatesofdawn_300.jpg",
            "The album's innovative sound and style established Pink Floyd as one of the key players in the emerging psychedelic rock scene of the late 1960s. The Piper at the Gates of Dawn is often cited as a landmark album in the history of rock music and has influenced countless musicians over the years. Its enduring popularity is a testament to the band's artistic vision and the enduring appeal of its groundbreaking sound."),
        Album(2, "A Saucerful of Secrets", "28 June 1968", "Let There Be More Light", "https://upload.wikimedia.org/wikipedia/en/5/54/Saucerful_of_secrets2.jpg",
            "The album showcases the band's willingness to experiment with new sounds and styles, while still retaining the psychedelic rock sound that they had become known for. A Saucerful of Secrets has become a fan favorite over the years and is often regarded as one of Pink Floyd's best albums, due to its groundbreaking sound and its historical significance as a bridge between the band's early period with Barrett and its later period with Gilmour."),
        Album(3, "More", "13 June 1969", "Green is the Colour", "https://upload.wikimedia.org/wikipedia/en/4/40/MoreCover.jpg",
            "'More' is often considered a transitional album in Pink Floyd's career, as it marked a shift from their psychedelic sound towards a more experimental and progressive style. It also marked the departure of founding member Syd Barrett and the arrival of new member David Gilmour, who would become an integral part of the band's sound in the years to come. The album's atmospheric and diverse tracks, ranging from dreamy instrumentals to haunting melodies, contribute to its status as a captivating soundtrack for the film 'More'."),
        Album(4, "Ummagumma", "7 November 1969", "Careful With That Axe, Eugene", "https://upload.wikimedia.org/wikipedia/en/1/16/PinkFloyd-album-ummagummastudio-300.jpg",
            "'Ummagumma' received mixed reviews upon its release but has since gained a cult following among Pink Floyd fans. It is considered a transitional album for the band, showcasing their evolution from a psychedelic rock band to a more experimental and progressive rock sound. It offers a unique and eclectic listening experience that reflects Pink Floyd's exploration of new musical territories during that period."),
        Album(5, "Atom Heart Mother", "2 October 1970", "Summer '68", "https://upload.wikimedia.org/wikipedia/en/2/2e/AtomHeartMotherCover.jpeg",
            "'Atom Heart Mother' is considered to be one of Pink Floyd's most ambitious and experimental albums, showcasing the band's willingness to push boundaries and explore new musical territory. Despite receiving mixed reviews upon its release, the album has since become a cult classic and a favorite among many Pink Floyd fans. The album stands as a testament to Pink Floyd's innovative spirit, blending orchestral arrangements, avant-garde elements, and progressive rock structures"),
        Album(6, "Relics", "14 May 1971", "Arnold Layne", "https://upload.wikimedia.org/wikipedia/en/1/18/Pink_Floyd_Relics_1971.jpg",
            "'Relics' provides an interesting snapshot of Pink Floyd's early career and showcases the band's evolution from their psychedelic roots to their more experimental sound. While some of the tracks may feel a bit dated, the album is still a must-listen for any Pink Floyd fan or anyone interested in the history of rock music. It offers a snapshot of Pink Floyd's early career, showcasing their evolution from psychedelic roots to experimentation, making it a must-listen for fans and rock music enthusiasts."),
        Album(7, "Meddle", "30 October 1971", "Echoes", "https://upload.wikimedia.org/wikipedia/en/d/d4/MeddleCover.jpeg",
            "''Meddle' is often regarded as a transitional album for Pink Floyd, as it marks the beginning of the band's more experimental period. The album's mix of psychedelic rock, progressive rock, and avant-garde influences helped pave the way for the band's later masterpieces, such as 'Dark Side of the Moon' and 'Wish You Were Here'. Overall, 'Meddle' remains a cornerstone of Pink Floyd's discography and a must-listen for any fan of progressive rock."),
        Album(8, "Obscured by Clouds", "2 June 1972", "Wots... Uh The Deal", "https://upload.wikimedia.org/wikipedia/en/e/ef/Pink_Floyd_-_Obscured_by_Clouds.jpg",
            "'Obscured by Clouds' may not be as iconic as some of Pink Floyd's other albums, but it remains a solid and enjoyable listen for both fans and newcomers alike. The album's mix of psychedelic rock, folk-inspired melodies, and more traditional rock elements helped bridge the gap between the band's earlier and later works and cemented their place as one of the most innovative and influential bands of the 20th century."),
        Album(9, "The Dark Side of the Moon", "1 March 1973", "Eclipse", "https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png",
            "'The Dark Side of the Moon' marked a significant departure from Pink Floyd's earlier works and established them as one of the most innovative and influential bands of the 1970s. The album's seamless blend of psychedelic rock, progressive rock, and avant-garde influences, combined with its thought-provoking lyrics and stunning visual design, helped redefine the possibilities of rock music and inspired countless musicians in the years that followed. Even today, 'The Dark Side of the Moon' remains a timeless masterpiece."),
        Album(10, "Wish You Were Here", "12 September 1975", "Shine On You Crazy Diamond", "https://upload.wikimedia.org/wikipedia/en/a/a4/Pink_Floyd%2C_Wish_You_Were_Here_%281975%29.png",
            "'Wish You Were Here' is widely regarded as one of Pink Floyd's greatest works and a masterpiece of progressive rock. The album's complex concept, which explores themes of absence, disillusionment, and the music industry, combined with the band's signature sound and stunning instrumental performances, helped redefine the possibilities of rock music and cemented Pink Floyd's place as one of the most innovative and influential bands of all time."),
        Album(11, "Animals", "21 January 1977", "Pigs (Three Different Ones),", "https://upload.wikimedia.org/wikipedia/en/7/74/Pink_Floyd-Animals-Frontal.jpg",
            "'Animals' is often regarded as one of Pink Floyd's darkest albums and a reflection of the band's disillusionment with the music industry and society at large. The album's mix of progressive rock, hard rock, and blues influences, combined with its thought-provoking lyrics and stunning visual design, helped establish Pink Floyd as one of the most innovative and influential bands of the 1970s. Even today, 'Animals' remains a powerful and timely commentary on the state of the world."),
        Album(12, "The Wall", "30 November 1979", "Another Brick in the Wall", "https://upload.wikimedia.org/wikipedia/en/1/13/PinkFloydWallCoverOriginalNoText.jpg",
            "'The Wall' is widely regarded as one of Pink Floyd's greatest works and a masterpiece of rock opera. The album's complex concept, which was later adapted into a film, combined with the band's signature sound and stunning instrumental performances, helped redefine the possibilities of rock music and cemented Pink Floyd's place as one of the most innovative and influential bands of all time. Even today, 'The Wall' remains a powerful and timeless commentary on the human condition."),
        Album(13, "The Final Cut", "21 March 1983", "The Final Cut", "https://upload.wikimedia.org/wikipedia/en/e/e4/FloydFC-Cover01.jpg",
            "'The Final Cut' is often regarded as a continuation of the themes explored in 'The Wall' and a reflection of the band's growing political activism. The album's mix of progressive rock, orchestral arrangements, and poignant lyrics, combined with its stunning visual design, helped establish Pink Floyd as one of the most innovative and influential bands of the 1980s. While not as commercially successful as some of the band's earlier works, 'The Final Cut' remains a powerful and poignant statement on the human cost of war."),
        Album(14, "A Momentary Lapse of Reason", "7 September 1987", "Learning to Fly", "https://upload.wikimedia.org/wikipedia/en/4/4e/MLoRLP01.jpg",
            "'A Momentary Lapse of Reason' is Pink Floyd's thirteenth studio album, released in 1987. Musically, the album showcases a departure from the band's earlier concept-driven works. David Gilmour takes the helm as the creative force, delivering his signature guitar mastery and emotive vocals throughout the album. The sound leans towards a more accessible and commercially oriented direction, blending progressive rock, art rock, and synthesizer-driven pop elements."),
        Album(15, "The Division Bell", "28 March 1994", "High Hopes", "https://upload.wikimedia.org/wikipedia/en/6/6e/Pink_Floyd_-_Division_Bell.jpg",
            "'The Division Bell' is often regarded as a return to form for Pink Floyd, as it marked the band's reunion with longtime collaborator Richard Wright and a renewed focus on musical collaboration and experimentation. The album's mix of progressive rock, electronic music, and atmospheric soundscapes, combined with its stunning visual design and innovative use of technology, helped establish Pink Floyd as one of the most innovative and influential bands of the 1990s."),
        Album(16, "The Endless River", "7 November 2014", "Louder Than Words", "https://upload.wikimedia.org/wikipedia/en/b/be/Pink_Floyd_-_The_Endless_River_%28Artwork%29.jpg",
            "'The Endless River' is often regarded as a final farewell to Pink Floyd and a celebration of the band's enduring legacy. The album's mix of ambient music, progressive rock, and atmospheric soundscapes, combined with its stunning visual design and innovative use of technology, helped establish Pink Floyd as one of the most innovative and influential bands of all time. Even today, 'The Endless River' remains a powerful and poignant tribute to the band's extraordinary career and the enduring power of their music.")
        )
}